### ISSUE TITLE
Subterranodon Taming

### ISSUE THREAD

**Issue by Noonyeyz** [AlexModGuy/AlexsCavesBetaTest#26]
Idk what Subterranodon's intended purpose is-but I think it's supposed to be a pseudo tame.
if possible Subterranodon's should be able to just either lose 'tamed' status after awhile or be able to be tamed by multiple different players.
I think their death announcements should also be removed from chat considering they are a pseudo tame (kinda like how striders or pigs don't have death messages)

**Comment by Prismarine-Pinky** [comment]
I don't think they're supposed to be pseudo-tames, because taming them for me has been fine, as you shift+R-click them to order them and regular R-click to ride them.

**Comment by AlexModGuy** [comment]
its not a pseudo tame at all its the full thing.

**Comment by Noonyeyz** [comment]
ogh didn't know...
