### ISSUE TITLE
Nuclear Furnaces cannot be constructed via Piston

### ISSUE THREAD

**Issue by Noonyeyz** [AlexModGuy/AlexsCavesBetaTest#37]
Pushing the final component into a nearly complete nuclear furnace doesn't create a nuclear furnace..

tbh you could consider this a feature as a means to give players the ability to create 2x2 boxes out of components without creating a furnace

**Comment by AlexModGuy** [comment]
it needs a player because it uses the direction of the player to determine the facing of the furnace.
