### ISSUE TITLE
Abyssal Biome Fog Flickering

### ISSUE THREAD

**Issue by Noonyeyz** [AlexModGuy/AlexsCavesBetaTest#43]
Not really sure what's causing it but it's pretty intense especially when it's near black and you're flashed with bright blue.... Happens seemingly randomly around Y 45...

B'oP and Alex's Mobs are installed

**Comment by AlexModGuy** [comment]
did a little tweaking, not sure if it will fix. I did add some configs to disable AC's water fog system though, if its a persistent problem.
