### ISSUE TITLE
Toxic Acid Pool Gen leaves a lot of holes and glitchy structures

### ISSUE THREAD

**Issue by Noonyeyz** [AlexModGuy/AlexsCavesBetaTest#44]
![2023-09-16_21 59 36](https://github.com/AlexModGuy/AlexsCavesBetaTest/assets/42457241/a04045fd-b3ac-4f5e-ad68-4660e9db539b)
![2023-09-16_21 56 52](https://github.com/AlexModGuy/AlexsCavesBetaTest/assets/42457241/071c4be0-f151-4652-a1c4-8d0e11f8ad55)
![2023-09-16_11 42 21](https://github.com/AlexModGuy/AlexsCavesBetaTest/assets/42457241/1dae2132-8852-4cce-a411-cfd7afbe81bd)

**Comment by Noonyeyz** [comment]
Really only happens in large toxic caves

**Comment by AlexModGuy** [comment]
cant/wontfix. it would require seinding block updates to each of those and loading extra chunks which would destroy server performance

**Comment by AlexModGuy** [comment]
![2023-09-17_13 23 15](https://github.com/AlexModGuy/AlexsCavesBetaTest/assets/8662109/2a89b758-73cc-4745-aaa4-bf4679a74187)
Was able to reduce it though, and fix it if its below a lake (the sides would require loading extra chunks unfortunately)
