### ISSUE TITLE
Missing Loot in Barrels in Toxic

### ISSUE THREAD

**Issue by Noonyeyz** [AlexModGuy/AlexsCavesBetaTest#46]
![2023-09-16_22 26 57](https://github.com/AlexModGuy/AlexsCavesBetaTest/assets/42457241/e78d089a-a2fb-4178-97b5-8b2a932774ca)
![2023-09-16_22 25 08](https://github.com/AlexModGuy/AlexsCavesBetaTest/assets/42457241/e1f0774e-dc0d-45a6-b1d0-e8f00b5bc76b)

These structures come with no loot :(

**Comment by AlexModGuy** [comment]
i think its intentional that only some have loot
