### ISSUE TITLE
Underzealot Feedback

### ISSUE THREAD

**Issue by Noonyeyz** [AlexModGuy/AlexsCavesBetaTest#56]
Underzealots are pretty neat this being said they can be a pain to deal with if they're in large groups or if larger more sinister monsters are around.
Here's some feedback regarding some problems.

1. Their burrowing animation is too slow and the immunity frames don't really make sense.
 -Personally don't mind the fact they have immunity frames, however it just feels like you should be able to hit them at a certain point.
 -We can resolve this by either making their immunity frames shorter or making the burrow anim faster
 -Also could be cool to add the chance that they don't burrow on first strike or maybe making it so they only burrow on low health. idk

 2. They don't full disappear, this is disorienting.
  -I don't know the logistics of this in code, I'm assuming there's a reason they don't fully disappear but if there isn't it would be cool if they could. 
  -If not I think the most disorienting part about them is the fact they still make sounds underground-if they could somehow be quiet whilst not above ground this would help immensely.
  
  3. Drops are a lil too common.
  -I think this has been corrected but yeah.

**Comment by AlexModGuy** [comment]
I
-made the dig anim faster
-removed invuln while digging
-tried to fix the fully dissapear thing but its really hard to do this with vanilla entities
-sound thing
-reduced how often they bury in combat
