### ISSUE TITLE
Animation Cancel Resistor Shield Flipping sides.

### ISSUE THREAD

**Issue by Noonyeyz** [AlexModGuy/AlexsCavesBetaTest#62]
Idk if this is intentional or resolvable. Stepping out of shift cancels the resistor shield anim

**Comment by AlexModGuy** [comment]
https://github.com/AlexModGuy/AlexsCavesBetaTest/assets/8662109/c99f6b1d-7ce0-41db-bc42-6a24257c185b

not able to replicate
