### ISSUE TITLE
structure(s?) don't generate loot in toxic caves

### ISSUE THREAD

**Issue by Gatetoh** [AlexModGuy/AlexsCavesBetaTest#64]
while exploring in creative mode, I noticed that specifically in the black cat head structure inside the barrel there wasn't any loot, I tought this was a bug, unless it's intentional

**Comment by AlexModGuy** [comment]
intentional unfortunately. the way some of these structures were built leaves no room to put a structure marker for loot above loot barrels - meaning some of them will be empty
